"""Generate Table XIV (the complete task registry) from ledger.win_readout.QUERIES.

The table IS the claim of Sec. III-B, so it must be the registry the readout
actually evaluates, not a transcription of it. Run from the repo root:

    .venv/bin/python scripts/gen_registry_table.py \
        > papers/RDWM_Every_Row_Is_An_Event/tables/tabA1_registry.tex
"""
import relbench.tasks as T
from ledger.win_readout import QUERIES

BOARD, HORIZON = {}, {}
for key in QUERIES:
    t = T.get_task(*key, download=False)
    BOARD[key] = "cls" if "BINARY" in str(t.task_type) else "reg"
    HORIZON[key] = t.timedelta.days


def esc(s):
    return str(s).replace("_", r"\_").replace("&", r"\&")


def co(name):
    """A column or table name, with break opportunities after the punctuation
    a denormalised name is built from. Without them a generated column such as
    SearchStream@SearchID.IsClick=1.0.n is one unbreakable box that runs off
    the page -- and an overfull \\hbox inside a p-column is not always
    reported, so the defect would be invisible in the log."""
    t = esc(name)
    for ch in ("@", ".", "=", r"\_"):
        t = t.replace(ch, ch + r"\hspace{0pt}")
    return r"{\fontsize{6.2}{7}\selectfont\texttt{%s}}" % t


def pred(q):
    ps = []
    if q.cat_in:
        _, c, v = q.cat_in
        ps.append(co(c) + r"$\,{\in}\,\{$%s$\}$"
                  % esc(", ".join(sorted(map(str, v)))))
    if q.cat_not:
        _, c, v = q.cat_not
        ps.append(co(c) + r"$\,{\notin}\,\{$%s$\}$"
                  % esc(", ".join(sorted(map(str, v)))))
    if q.num_le:
        _, c, thr = q.num_le
        ps.append(co(c) + r"$\,{\le}\,%g$" % thr)
    if q.num_gt:
        _, c, thr = q.num_gt
        ps.append(co(c) + r"$\,{>}\,%g$" % thr)
    return r" $\wedge$ ".join(ps) if ps else r"\textit{none}"


def label(q):
    """The functional the benchmark calls the label. The aggregated column is
    named inside the subscript rather than given a column of its own: it
    applies to only five of the 21 rows, and an almost-empty column costs more
    width here than it earns."""
    if q.agg == "occur":
        return (r"$\mathbf{1}[N^{\phi}_T{=}0]$" if q.absence
                else r"$\mathbf{1}[N^{\phi}_T{>}%d]$" % q.k)
    c = r"\mathtt{%s}" % (esc(q.value[1]).replace(r"\_", r"\_")
                          if q.value else "")
    return {"count": r"$N^{\phi}_T$",
            "sum": r"$S^{\phi}_{T}[%s]$" % c,
            "mean": r"$S^{\phi}_{T}[%s]\,/\,N^{\phi}_T$" % c,
            "ratio": r"$N^{\phi}_T/N^{\psi}_T$"}[q.agg]


FLAG = {"denorm_fk": r"\tf{fk}", "child_aggs": r"\tf{ca}",
        "path_expand": r"\tf{pe}"}

rows = {"cls": [], "reg": []}
for key, q in QUERIES.items():
    db, tk = key
    rows[BOARD[key]].append(
        r"\ds{%s} & \task{%s} & %d & \textsc{%s} & %s & %s & %s & %s\\" % (
            esc(db), esc(tk), HORIZON[key], q.agg,
            ", ".join(co(t) for t in q.tables),
            pred(q),
            label(q),
            r"\,".join(FLAG[n] for n in q.needs) if q.needs else r"\na"))

P = print
P(r"""%% GENERATED by scripts/gen_registry_table.py -- do not edit by hand.
\begin{table*}[t]
\centering
\newcommand{\tf}[1]{{\footnotesize\textsc{#1}}}
\caption{\textbf{The complete task registry: all \numTasks{} RelBench entity
tasks as window-aggregate queries.} This is the evidence for the reduction of
\cref{sec:reduction}, and it is \emph{generated} from the \texttt{QUERIES}
dictionary of \texttt{ledger/win\_readout.py} rather than transcribed, so what
is printed is exactly what the readout evaluates. Every row states a
\emph{question} and never a label: the fact tables whose rows may qualify, the
predicate $\phi$ that admits them, the horizon $D$ in days, and the
functional of the window aggregate that the benchmark calls the label---with
the aggregated column, where there is one, named inside its subscript. Nothing in any column was fitted; each entry
was read off that task's \texttt{make\_table} in \texttt{relbench/tasks/}. The
last column names the corpus transformations a query's columns depend on
(\cref{sec:tokens}): \tf{fk}~foreign-key denormalisation, \tf{ca}~child
aggregates, \tf{pe}~target-side path expansion.}
\label{tab:registry}
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabular}{@{}l l c l >{\raggedright\arraybackslash}p{25mm} >{\raggedright\arraybackslash}p{45mm} l c@{}}
\toprule
database & task & $D$ & family & fact tables & predicate $\phi$ &
  label & corpus\\
\midrule
\rowcolor{RowTint}\multicolumn{8}{@{}l}{\textbf{Classification board}\quad 12 tasks, scored by test AUROC}\\""")
for r in rows["cls"]:
    P(r)
P(r"\midrule")
P(r"\rowcolor{RowTint}\multicolumn{8}{@{}l}{\textbf{Regression board}\quad 9 tasks, scored by test NMAE}\\")
for r in rows["reg"]:
    P(r)
P(r"""\bottomrule
\end{tabular}

\vspace{3pt}
{\footnotesize
\textbf{What the table shows, and what it does not.} All \numTasks{} rows
compute the same object---a count of qualifying events in $\win$, or a sum of
one column over them---and the three rightmost columns are the only
things that vary. That is the reduction, stated exhaustively rather than argued, and it is
a claim about the \emph{benchmark}: the correspondence is checkable against
RelBench's own source and does not depend on our model being any good.

\textbf{Denominators.} The two \textsc{ratio} rows share their numerator's
fact table, so the table above lists it once. For \ds{rel-avito}
\task{ad-ctr}, $\psi$ is the unfiltered rate over the same
\texttt{SearchStream} rows---clicks over impressions. For \ds{rel-trial}
\task{site-success}, $\psi$ keeps the \texttt{outcome\_type} ${=}$
\texttt{Primary} filter and drops the $p$-value one.

\textbf{Three rows carry approximations,} which we state rather than bury.
\task{study-adverse} filters a sum, and the window head carries the marginal
rate per category and the marginal sum but not their joint, so a filtered sum
is estimated as the unfiltered sum scaled by the filter's share of the rate.
\task{study-outcome} and \task{site-success} compose their two predicates as
independent marginals; in \task{site-success} the \texttt{Primary} factor
therefore \emph{cancels} between numerator and denominator, leaving the
marginal significant-analysis rate over every outcome type. That predicate is
kept because it names the intended question and becomes exact the moment the
head carries a joint---but it is doing no work today and must not be read as
though it were. Both tasks also drop the benchmark's third condition
(\texttt{p\_value\_modifier} ${\neq}$ \texttt{>}), which moves little mass and
would compound the independence assumption further.

\textbf{Declared dependencies are enforced, not documented.} A query naming a
derived column is \emph{unanswerable} against a corpus built without the
corresponding transformation, and the failure is silent: the filter degrades
to the unfiltered rate and the task still returns a plausible number. This is
not hypothetical---it is what held \ds{rel-avito} \task{user-clicks} at $48.4$
AUROC. The dependency is therefore carried in the query object and refused at
evaluation time rather than left to the operator to remember.}
\end{table*}""")
