"""Generate Table XVI (per-task readout) from the code and the recorded
validation decision, not by hand.

Two things are selected per task and both are printed here: the ARITHMETIC,
which `ledger.win_readout.classify` resolves from the query itself, and the
COLUMN (label-free or probe), which was chosen on validation and is recorded
in scripts/readout_choice.json. Usage:

    .venv/bin/python scripts/gen_readout_table.py \
        > papers/RDWM_Every_Row_Is_An_Event/tables/tabA3_readout_choice.tex
"""
import json
import relbench.tasks as T
from ledger.win_readout import QUERIES, _is_filtered

CHOICE = json.load(open("scripts/readout_choice.json"))

# The arithmetic each family resolves to, as it appears in Sec. III-G.
FORM_TEX = {
    "poisson":  r"Poisson tail",
    "binomial": r"binomial tail",
    "fraction": r"per-event rate",
    "count":    r"count quantile",
    "sum":      r"sum quantile",
    "mean":     r"bucketed mean",
    "ratio":    r"rate quotient",
}
FORM_EQ = {
    "poisson":  r"$1-e^{-\hat\lambda_{\phi}}$, or \cref{eq:ptail} for $k{\ge}1$",
    "binomial": r"\cref{eq:binom}",
    "fraction": r"$\hat\lambda_{\phi}/\hat\lambda$",
    "count":    r"$e^{\hat q_{0.5}}-1$",
    "sum":      r"$\mathrm{slog}^{-1}(\hat q_{0.5})$",
    "mean":     r"$\sum_b \hat\lambda_b m_b / \sum_b \hat\lambda_b$",
    "ratio":    r"$\hat\lambda_{\phi}/\hat\lambda_{\psi}$",
}


def resolved_form(q):
    """Reproduce classify()'s resolution, so the table cannot drift from it."""
    if q.agg != "occur":
        return q.agg
    form = q.form
    if form == "auto":
        form = "poisson" if q.k >= 1 else (
            "fraction" if _is_filtered(q) else "poisson")
    if form != "poisson" and _is_filtered(q):
        return "fraction" if (form == "fraction" and q.k == 0) else "binomial"
    return "poisson"


def esc(s):
    return str(s).replace("_", r"\_")


rows = {"cls": [], "reg": []}
for key, q in QUERIES.items():
    db, tk = key
    t = T.get_task(db, tk, download=False)
    board = "cls" if "BINARY" in str(t.task_type) else "reg"
    col = CHOICE["%s %s" % (db, tk)]
    rows[board].append(
        r"\ds{%s} & \task{%s} & %s & %s\\" % (
            esc(db), esc(tk), FORM_TEX[resolved_form(q)],
            r"\textsc{probe}" if col == "probe" else r"\textbf{\textsc{zero}}"))

nz = sum(1 for v in CHOICE.values() if v == "zero")

P = print
P(r"""%% GENERATED by scripts/gen_readout_table.py -- do not edit by hand.
\begin{table}[t]
\centering
\caption{\textbf{What is chosen per task, and on what.} Two decisions are made
per task and neither sees a test label. The \emph{arithmetic} is resolved from
the query itself by \texttt{classify} in \texttt{ledger/win\_readout.py}---the
column below reproduces that resolution rather than restating it---and the
\emph{column} is whichever of the label-free readout and the \supportN-row
linear probe won on validation. \textsc{zero} uses no labels anywhere and wins
%d of the \numTasks{} tasks.}
\label{tab:readoutchoice}
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}llll@{}}
\toprule
database & task & arithmetic & column\\
\midrule
\rowcolor{RowTint}\multicolumn{4}{@{}l}{\textbf{Classification}}\\""" % nz)
for r in rows["cls"]:
    P(r)
P(r"\midrule")
P(r"\rowcolor{RowTint}\multicolumn{4}{@{}l}{\textbf{Regression}}\\")
for r in rows["reg"]:
    P(r)
P(r"""\bottomrule
\end{tabular}

\vspace{2pt}
{\footnotesize
\emph{Poisson tail} is $1-e^{-\hat\lambda_{\phi}}$, or \cref{eq:ptail} when
$k{\ge}1$; \emph{binomial tail} is \cref{eq:binom}; \emph{per-event rate} is
$\hat\lambda_{\phi}/\hat\lambda$; the quantile, bucketed-mean and quotient
forms are those of \cref{tab:coverage}.

The arithmetic is a property of the \emph{data}, not of the task. An
occurrence label with $k{\ge}1$ asks for an absolute count, where the Poisson
tail on the qualifying rate is the right object; a filtered $k{=}0$ label asks
whether any single event qualifies, where the per-event probability is, because
the count is near-constant and can be \emph{anti}-correlated with the label---on
\ds{rel-event} \task{user-repeat} the historical yes-fraction alone scores
$70.3$ while the event count scores $41.4$. Two tasks override the rule
explicitly through \texttt{Q.form}.}
\end{table}""")
