"""Generate Table XV (per-database configuration) from the shipped checkpoints.

Read from the checkpoints named in scripts/board_ckpts.json rather than from a
launch script, so the table describes the weights that produced the numbers in
the paper and not a command someone believes was run. Usage:

    .venv/bin/python scripts/gen_hparam_table.py \
        > papers/RDWM_Every_Row_Is_An_Event/tables/tabA2_hparams.tex
"""
import json
import torch

CK = json.load(open("scripts/board_ckpts.json"))

# Everything below is identical in every run; it belongs in the caption, not
# in a column of sevens.
SHARED = ["dim", "layers", "heads", "max_len", "batch_rows", "n_neg", "lr",
          "warmup", "min_lr_frac", "seed", "n_query", "query_feats",
          "win_buckets", "win_max_events", "w_when", "w_where", "w_who",
          "w_what", "w_win", "amp", "cutoff", "state_momentum",
          "window_head", "no_ema_write"]

rows, shared_vals, seen = [], {}, {}
for key, path in CK.items():
    d = torch.load(path, map_location="cpu", weights_only=False)
    a = d["args"]
    a = a if isinstance(a, dict) else vars(a)
    for k in SHARED:
        shared_vals.setdefault(k, set()).add(repr(a.get(k)))
    (metric, value), = d["metric"].items()
    flags = [n for n, f in (("fk", "denorm_fk"), ("ca", "child_aggs"))
             if a.get(f)]
    tag = a["tag"]
    row = dict(
        key=key, tag=tag,
        db=key.split("/")[0],
        task=key.split("/")[1] if "/" in key else None,
        ent=a["entity"].replace(",", ", "),
        states=a["states"],
        flags=r"\,".join(r"\tf{%s}" % f for f in flags) or r"\na",
        # Older runs predate the flag and ran on its default of 2;
        # marked with a dagger rather than silently printed as if set.
        min_hist=a.get("min_hist"), min_hist_default="min_hist" not in a,
        self_rows=a.get("self_rows"),
        budget=a["steps"], step=d["step"],
        metric="AUROC" if "auroc" in metric else "NMAE",
        value=float(value))
    rows.append(row)

varying = {k for k, v in shared_vals.items() if len(v) > 1}
assert not varying - {"workers"}, f"not actually shared: {varying}"


def esc(s):
    return str(s).replace("_", r"\_")


def fmt(r):
    name = r"\ds{%s}" % esc(r["db"])
    if r["task"]:
        name += r"\,/\,\task{%s}" % esc(r["task"])
    return (r"\texttt{%s} & %s & \texttt{%s} & %s & %s & %s & %s & "
            r"%s & %s & %.4f\\" % (
                esc(r["tag"]), name, esc(r["ent"]), r["states"], r["flags"],
                (r"$2^{\dagger}$" if r["min_hist_default"]
                 else r["min_hist"]),
                r"\checkmark" if r["self_rows"] else r"\na",
                "{:,}".format(r["budget"]).replace(",", "{,}"),
                r"\best{%s}" % "{:,}".format(r["step"]).replace(",", "{,}"),
                r["value"]))


rows.sort(key=lambda r: (r["task"] is not None, r["db"]))
P = print
P(r"""%% GENERATED by scripts/gen_hparam_table.py -- do not edit by hand.
\begin{table*}[t]
\centering
\newcommand{\tf}[1]{{\footnotesize\textsc{#1}}}
\caption{\textbf{Every configuration that varies, and the checkpoint each
number in this paper was produced by.} Values are read out of the shipped
checkpoints rather than out of a launch script, so this describes the weights
that were scored and not a command we believe was run. \emph{Everything not
listed here is identical across all nine runs}: %d layers of width %d with %d
heads, context %d, %d packed rows per step, %d sampled negatives, AdamW at
$3{\times}10^{-4}$ with %d warm-up steps and cosine decay to %g of peak, all
five loss weights initialised to $1.0$, bf16 autocast, seed $0$, and a corpus
cut at the \emph{validation} timestamp. Six knobs vary, and each is forced by
the database rather than tuned: which table holds the entities, whether entity
states are learned embeddings or non-parametric slots, which corpus
transformations the tasks on that database need (\cref{tab:registry}), the
minimum history length, whether an entity's own row is admitted to its stream,
and where validation stopped the run.}
\label{tab:hparams}
\scriptsize
\setlength{\tabcolsep}{4pt}
\begin{tabular}{@{}llllccccrr@{}}
\toprule
& & & & & \multicolumn{2}{c}{history} & \multicolumn{2}{c}{steps} & \\
\cmidrule(lr){6-7}\cmidrule(lr){8-9}
run & database\,/\,task & entity table(s) & states & corpus &
  \makecell{min.} & \makecell{self} & budget & selected & val.\\
\midrule""" % (12, 512, 8, 512, 16, 256, 100, 0.1))
for r in rows:
    if r["task"] is not None:
        break
    P(fmt(r))
P(r"\midrule")
P(r"\rowcolor{RowTint}\multicolumn{10}{@{}l}{\textbf{Additional \ds{rel-stack} runs}}\\")
for r in rows:
    if r["task"] is not None:
        P(fmt(r))
P(r"""\bottomrule
\end{tabular}

\vspace{3pt}
{\footnotesize
\textbf{The selected step is the finding here.} Every run was given a budget
of $4$--$6$k steps, and on four of the nine the checkpoint that won on
validation is an \emph{early} one---step $500$ of $6{,}000$ on \ds{rel-stack}
and \ds{rel-trial}, $1{,}750$ on \ds{rel-avito}, $2{,}000$ on the second
\ds{rel-stack} run. Training longer made those models worse at the window
statistics the readout consumes, and only a validation-selected checkpoint
catches that. Before we had a selection protocol we exported whichever
checkpoint a run happened to end on; \cref{tab:defects} records what that cost.
The right-hand column is the selection metric on the single monitored task
named by \texttt{-{}-eval\_entity}, not a board score---it exists to rank
checkpoints within one run and must not be compared across rows.

$^{\dagger}$Predates the \texttt{-{}-min\_hist} flag; the value shown is the
default that was in force, not a setting we chose.

\textbf{Two databases use non-parametric states.} \ds{rel-hm} and
\ds{rel-avito} have catalogues too large for a learned embedding per entity to
be worth its gradient: the slot is written by assignment from the trunk's own
output and read back as an input feature (\cref{sec:tokens}). On \ds{rel-avito}
and \ds{rel-trial} the \texttt{-{}-no\_ema\_write} flag must be \emph{off} or
every state stays at zero, which is a silent failure---the model trains, the
loss falls, and the retrieval head scores a table of zeros.

\textbf{The one entry we would rather not report} is that \ds{rel-stack} needs
three checkpoints rather than one. \task{post-votes} predicts a count over
\texttt{posts}, so its entities are posts and not users, and a model whose
state table is keyed by user cannot answer it at all; its two user-keyed tasks
were then won by a later run of the same configuration. Both are listed rather
than folded away. This is a real limit of one-model-per-database and we count
it against the claim rather than around it.}
\end{table*}""")
